// Broad safety net: every prerendered route loads, hydrates and renders clean,
// in every published locale.
//
// WHY. The site emits 84 prerendered documents (14 pages x 6 locales) and
// nothing looked at any of them in a browser. scripts/prerender.mjs checks the
// OUTPUT (sitemap coverage, canonical shape, internal links, article bodies) but
// never runs the bundle, so the whole hydration step was unverified and the last
// router upgrade was signed off by clicking through pages by hand.
//
// NO SAMPLING, NO CAP, because it turned out not to be needed. Measured on an
// M-series laptop against `vite preview`: ~120ms per route on ONE reused page,
// so the 84-route sweep is ~10.3s and the whole file (sweep, planted-mismatch
// canary, three navigation tests, the 404 page) runs in 12.1s to 13.5s over a
// dozen runs, the spread being other work on the same preview server. A
// fresh page per route costs 288ms/route (24.2s) and found exactly the same
// problems, so the reused page wins. Nothing here is sampled or capped: the
// only thing deliberately left out is dist/404.html's HTTP STATUS (see the last
// test for why), and that exclusion is a test of its own rather than a gap.
//
// TWO HARNESS FACTS THAT SHAPE EVERYTHING BELOW
//
// 1. `vite preview` does NOT resolve a clean URL to its directory index. It
//    serves dist/index.html (the SPA shell) with a 200 for every extensionless
//    path without a trailing slash, so GET /de/about returns the ENGLISH
//    homepage and only GET /de/about/ returns the prerendered German page.
//    Production does resolve it (the GitHub Pages origin serves
//    /services/index.html for /services), so requesting the sitemap URL verbatim
//    here would test the SPA fallback instead of the artifact. Document requests
//    are therefore rewritten to the directory form (installProductionUrlShape).
//
//    Appending the slash to the URL BAR instead is a trap. The app reads
//    useLocation().pathname and Navigation gates its sticky CTA on
//    `delocalizePath(pathname) === "/services"`, so with /services/ in the
//    address bar the client renders one extra "Book a Session" the server did
//    not and all six /services routes report a hydration mismatch the shipped
//    site does not have. Rewriting the RESPONSE and keeping the URL canonical is
//    what makes the sweep honest.
//
// 2. React's hydration mismatch is a MINIFIED error in this build, not a
//    warning. helpers.collectErrors() has a branch for warnings that look like
//    React diagnostics, but `vite build` strips those message strings, so a
//    real mismatch arrives as `pageerror: Minified React error #418/#422/#425`
//    through the pageerror hook instead. Verified by planting one, see
//    "the mismatch detector itself is not asleep" below.

import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { BASE, openBrowser, pageAt, markSpa, stayedSpa,
  HYDRATED,
} from "./helpers.mjs";

// page.evaluate/waitForFunction callbacks are serialised and run in the BROWSER,
// so they use globals this Node process does not have. eslint.config.js gives
// **/*.mjs node globals only (correct: that block exists for the build scripts)
// and ESLint 9 dropped /* eslint-env */. helpers.mjs trips the same rule; a
// `tests/e2e/**` block with globals.browser would retire both and this line too.
/* global document, requestAnimationFrame */

// --- route list, derived from the built output ------------------------------

// dist/sitemap.xml is generated by scripts/generate-feeds.mjs from the SAME
// route array prerender.mjs renders, and prerender.mjs fails the build if an
// emitted indexable page is missing from it. So it is the one list that cannot
// drift from the emitted pages, which is why a new route or a new blog post
// joins this sweep with no edit here. A hardcoded list would go stale silently,
// and silence is the failure mode this file exists to remove.
const sitemapResponse = await fetch(`${BASE}/sitemap.xml`);
if (!sitemapResponse.ok) {
  // Reached by running `node --test` directly instead of `npm run test:e2e`
  // (scripts/e2e.mjs is what starts vite preview and sets E2E_BASE).
  throw new Error(
    `GET ${BASE}/sitemap.xml returned ${sitemapResponse.status}. ` +
      "The built site must be served at E2E_BASE before this suite can derive its route list.",
  );
}
const sitemapXml = await sitemapResponse.text();

// <loc> is the route's CANONICAL URL (prerender.mjs passes `canonical` straight
// through), which is why it can be compared byte-for-byte against the served
// page's <link rel="canonical"> further down.
const locs = [...sitemapXml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);

// The published locale set, from the sitemap's hreflang alternates rather than
// from the <loc> paths: reading a different part of the XML keeps "does every
// published locale have pages?" from being circular, so a locale that was
// published but never emitted still shows up and fails below.
const advertisedLocales = [
  ...new Set(
    [...sitemapXml.matchAll(/hreflang="([a-z-]+)"/g)]
      .map((m) => m[1])
      .filter((l) => l !== "x-default"),
  ),
];

// The source locale renders at the ROOT, every other under /{locale}/. Derived:
// it is the advertised locale that never appears as a path prefix.
const paths = locs.map((l) => new URL(l).pathname);
const prefixesSeen = new Set(
  paths.map((p) => /^\/([a-z]{2})(?:\/|$)/.exec(p)?.[1]).filter(Boolean),
);
const SOURCE_LOCALE = advertisedLocales.find((l) => !prefixesSeen.has(l));

/** The locale a route's URL declares: its prefix, or the source locale at the root. */
function localeOf(pathname) {
  const prefix = /^\/([a-z]{2})(?:\/|$)/.exec(pathname)?.[1];
  // Membership-tested rather than pattern-matched, so a future two-letter
  // top-level route (say /ai) is not mistaken for a locale prefix.
  return prefix && advertisedLocales.includes(prefix) ? prefix : SOURCE_LOCALE;
}

const routes = locs.map((url) => {
  const pathname = new URL(url).pathname;
  return { url, pathname, locale: localeOf(pathname) };
});

// --- browser ---------------------------------------------------------------

let browser;
let page;
let errors;

/**
 * Make this origin answer a canonical URL the way production does.
 *
 * Only same-origin DOCUMENT requests with no extension and no trailing slash are
 * touched, and only their RESPONSE: the address bar keeps the canonical form, so
 * anything reading location.pathname sees what a real visitor's browser would
 * (harness fact 1). `corrupt` is used by one test, to plant a mismatch.
 */
async function installProductionUrlShape(target, { corrupt } = {}) {
  await target.route("**/*", async (route) => {
    const request = route.request();
    const url = new URL(request.url());
    const isCleanRoute =
      request.resourceType() === "document" &&
      url.origin === BASE &&
      !url.pathname.endsWith("/") &&
      !/\.[a-z0-9]+$/i.test(url.pathname);

    const response = isCleanRoute
      ? await route.fetch({ url: `${url.origin}${url.pathname}/${url.search}` })
      : await route.fetch();

    if (!corrupt || request.resourceType() !== "document") {
      return route.fulfill({ response });
    }
    return route.fulfill({ response, body: corrupt(await response.text()) });
  });
}

// HYDRATED now lives in ./helpers.mjs, so every suite that needs to know whether
// the client actually ran uses the same verified predicate instead of a copy.

/**
 * Navigate to a canonical route URL and return once it is hydrated AND any
 * console/page errors it produced have reached this process.
 *
 * That second half is load-bearing and was nearly missed. With a planted
 * mismatch the errors array still held 0 entries at the moment HYDRATED went
 * true, and all 4 after one round trip spanning two frames (~10ms): React reports
 * through onRecoverableError during the commit, so the event has already fired in
 * the page and it is the CDP delivery that lags. Dropping the two lines below
 * makes the canary fail with "Collected: []", which is what a silently vacuous
 * error check looks like. networkidle also settles it, at ~500ms per route (42s
 * across the sweep) to catch nothing extra.
 */
async function visit(target, pathname) {
  const response = await target.goto(BASE + pathname, { waitUntil: "load" });
  await target.waitForFunction(HYDRATED, null, { timeout: 15000 });
  await target.evaluate(
    () => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r))),
  );
  return response;
}

before(async () => {
  browser = await openBrowser();
  // 1280x900 renders the DESKTOP navigation (the md: breakpoint), which is what
  // the SPA chain clicks. The sweep is viewport-independent.
  ({ page, errors } = await pageAt(browser, 1280, 900));
  await installProductionUrlShape(page);
});

after(async () => {
  await browser?.close();
});

// --- the route list itself --------------------------------------------------

// A sweep over an empty list passes every assertion in this file, so the list is
// checked before it is used. The floors sit at the failure mode, not at today's
// inventory: a broken parse or a filter typo collapses the list to zero or a
// handful, while deleting a page or two stays far above them. Pinning 84 would
// make every new blog post a red build.
test("the route list came from the sitemap and covers every published locale", () => {
  assert.ok(SOURCE_LOCALE, `no source locale among ${advertisedLocales.join(", ")}`);
  assert.ok(advertisedLocales.length >= 2, "sitemap advertises fewer than 2 locales");
  assert.ok(routes.length >= 30, `only ${routes.length} routes parsed out of the sitemap`);
  assert.ok(
    routes.some((r) => r.pathname === "/"),
    "the site root is not in the sitemap",
  );

  const perLocale = new Map(advertisedLocales.map((l) => [l, 0]));
  for (const r of routes) perLocale.set(r.locale, perLocale.get(r.locale) + 1);
  const thin = [...perLocale].filter(([, n]) => n < 5);
  assert.deepEqual(
    thin,
    [],
    `locales advertised in hreflang but with almost no emitted routes: ${JSON.stringify(thin)}`,
  );
});

// --- the sweep -------------------------------------------------------------

// One test per locale (6 tests for 84 routes) rather than 84 tests: readable
// output, and a failure still names the exact route because each locale collects
// ALL its problems and reports them together. Stopping at the first bad route
// would hide the other 13 and turn one broken shared component into a bisect.
for (const locale of advertisedLocales) {
  const group = routes.filter((r) => r.locale === locale);

  test(`every ${locale} route loads, hydrates and renders clean (${group.length} routes)`, async () => {
    const problems = [];

    for (const route of group) {
      const errorsBefore = errors.length;
      const response = await visit(page, route.pathname);
      const raw = await response.text();

      const say = (msg) => problems.push(`${route.pathname}: ${msg}`);

      if (response.status() !== 200) say(`HTTP ${response.status()}`);

      // <html lang> read from the SERVED document, not from the live DOM. Only a
      // client-side locale switch ever touches document.documentElement.lang
      // (LanguageSwitcher), so on a fresh load the two agree anyway, and reading
      // the served bytes is what a crawler that runs no JS gets.
      const lang = /<html\b[^>]*\blang="([^"]*)"/.exec(raw)?.[1];
      if (lang !== locale) say(`<html lang> is ${lang ?? "MISSING"}, expected ${locale}`);

      // Document identity. Every prerendered page self-canonicalizes and the
      // sitemap <loc> IS that canonical, so this pins "the server gave us the
      // document for THIS route". It is what keeps the English half of the sweep
      // from being weak: the SPA fallback also carries lang="en", one <h1> and a
      // non-empty <title>, so lang alone cannot tell a never-emitted /about from
      // a served one. Verified by removing the URL rewrite, which is what a
      // missing route looks like: all 14 English routes then failed here (and on
      // the title comparison, and on the resulting hydration mismatch).
      //
      // Attribute order matters: react-helmet emits
      // `<link data-react-helmet="true" rel="canonical" ...>`, so a rel-first
      // regex silently matches nothing on every non-home page. Same trap is
      // documented twice in scripts/prerender.mjs.
      const canonicalTag = [...raw.matchAll(/<link\b[^>]*>/g)]
        .map((m) => m[0])
        .find((tag) => /rel="canonical"/.test(tag));
      const canonical = canonicalTag?.match(/href="([^"]+)"/)?.[1];
      if (canonical !== route.url) {
        say(`canonical is ${canonical ?? "MISSING"}, expected ${route.url}`);
      }

      // Exactly one h1, counted on the HYDRATED DOM (the rendered page is what
      // gets read and scored). Two is the realistic regression: a page heading
      // plus a block component that also renders one.
      const h1s = await page.locator("h1").count();
      if (h1s !== 1) say(`${h1s} <h1> elements, expected exactly 1`);

      // The served <title> and the hydrated one must AGREE. "Non-empty" alone is
      // close to a free pass: prerender.mjs already refuses to emit a page with
      // an empty title (injectRouteHead throws), and a dead client-side helmet
      // would just leave the served title in place, so nothing would be blank.
      // Comparing the two catches the served head and the client render
      // disagreeing about which page this is. The empty check stays for the
      // homepage, the one route prerender does not guard (it keeps the static
      // template head verbatim).
      //
      // Decoded with the browser's own parser, not an entity table: the real
      // titles already carry &amp; and &#x27;, and hardcoding today's two would
      // break on the first title containing a quote.
      const rawTitle = /<title\b[^>]*>([\s\S]*?)<\/title>/.exec(raw)?.[1] ?? "";
      const served = await page.evaluate((s) => {
        const el = document.createElement("textarea");
        el.innerHTML = s;
        return el.value.trim();
      }, rawTitle);
      const hydrated = (await page.title()).trim();
      if (!served) say("served <title> is empty");
      else if (served !== hydrated) {
        say(`title drifted on hydration: served ${JSON.stringify(served)}, hydrated ${JSON.stringify(hydrated)}`);
      }

      // Console errors, uncaught exceptions and (in a dev build) hydration
      // warnings, sliced out of the live array around this navigation. A late
      // arrival lands on the NEXT route's slice: still a failure, wrong name.
      for (const e of errors.slice(errorsBefore)) say(e);
    }

    assert.deepEqual(problems, [], `\n  ${problems.join("\n  ")}\n`);
  });
}

// --- the mismatch detector, checked against a planted mismatch -------------

// "No route logs a hydration mismatch" is the highest-value assertion in this
// file and the easiest one to have silently switched off: the build strips
// React's warning text (harness fact 2) and the mismatch is reported a beat
// after the hydration signal (see visit()). Either turns the sweep's error check
// into a no-op with nothing to show for it, so the detector is exercised on
// purpose. This corrupts the h1 TEXT of the prerendered /about document in
// flight and leaves the bundle alone, which is precisely a server/client
// divergence. If the sweep can pass while this fails, the sweep is lying.
test("the mismatch detector itself is not asleep", async () => {
  const { page: canary, errors: canaryErrors } = await pageAt(browser, 1280, 900);
  await installProductionUrlShape(canary, {
    corrupt: (html) =>
      html.replace(
        /(<h1\b[^>]*>)([^<]{5,})/,
        (_, open) => `${open}DELIBERATELY WRONG PRERENDERED TEXT`,
      ),
  });

  await visit(canary, "/about");
  // POLL for the diagnostic rather than trusting visit()'s two-frame wait. That
  // budget is enough on a fast laptop and measured NOT to be on a CI runner, where
  // CDP delivery of the console event lags further: the canary failed there with
  // "Collected: []", which is exactly what it exists to detect and would have read
  // as the detector being broken. The error arrives in milliseconds when it arrives
  // at all, so a genuinely absent diagnostic still fails in about a second.
  const isReact = (e) => /Minified React error #(418|422|423|425)|hydrat|did not match/i.test(e);
  const deadline = Date.now() + 5000;
  let react = canaryErrors.filter(isReact);
  while (react.length === 0 && Date.now() < deadline) {
    await new Promise((resolve) => setTimeout(resolve, 50));
    react = canaryErrors.filter(isReact);
  }
  assert.ok(
    react.length > 0,
    `a planted hydration mismatch produced no React diagnostic. Collected: ${JSON.stringify(canaryErrors)}`,
  );
  await canary.close();
});

// --- client-side navigation ------------------------------------------------

/**
 * Click an in-page link and wait for the DESTINATION to be on screen.
 *
 * The wait is on the <h1> TEXT changing, not on the URL and not on an <h1>
 * existing. react-router updates history before React commits the new tree, and
 * every page here has exactly one <h1> at all times, so both of the obvious
 * waits let the next assertion read the OLD view and pass (this file failed that
 * way first). Chains are ordered so consecutive pages have different headings,
 * which keeps it assertable without hardcoding copy translation churn breaks.
 *
 * A router regression that leaves the old view mounted times out here, which is
 * the failure this whole test exists to catch, so the timeout is the assertion.
 */
async function clickTo(href, previousH1) {
  // `:visible` because the same href exists in the desktop nav, the footer and
  // the (hidden) mobile overlay; .first() alone can resolve to a hidden node and
  // hang the click.
  const link = page.locator(`a[href="${href}"]:visible`).first();
  // Existence is asserted separately because "the link is not there" is a
  // different regression from "the click did nothing", and because clicking a
  // locator that matches nothing otherwise stalls on Playwright's 30s default
  // and reports a bare timeout (measured: 30.6s, no useful message).
  try {
    await link.waitFor({ state: "visible", timeout: 5000 });
  } catch {
    assert.fail(`no visible <a href="${href}"> on ${new URL(page.url()).pathname} to click`);
  }
  await link.click();
  await page.waitForURL(BASE + href);
  try {
    await page.waitForFunction(
      (prev) => {
        const h1s = document.querySelectorAll("h1");
        return h1s.length === 1 && h1s[0].innerText.trim() !== prev;
      },
      previousH1,
      { timeout: 5000 },
    );
  } catch {
    const h1s = await page.locator("h1").allInnerTexts();
    assert.fail(
      `${href}: the view never changed after the click. ` +
        `<h1> was ${JSON.stringify(previousH1)} before and is now ${JSON.stringify(h1s)}.`,
    );
  }
  return (await page.locator("h1").first().innerText()).trim();
}

// A router regression can break only the SECOND hop (a stale history listener, a
// basename change, a Link that resolves against the wrong location), so one
// click proves nothing. The chain is 5 hops and every hop is checked.
test("five Link clicks in a row navigate client-side, without a reload", async () => {
  await visit(page, "/");
  await markSpa(page);

  const errorsBefore = errors.length;
  let previousH1 = (await page.locator("h1").first().innerText()).trim();

  for (const href of ["/about", "/philosophy", "/blog/", "/contact", "/services"]) {
    previousH1 = await clickTo(href, previousH1);
    assert.equal(await stayedSpa(page), true, `${href} triggered a full page reload`);
  }

  // document.title is deliberately NOT asserted per hop: react-helmet applies it
  // in an effect, so it lags the DOM by one navigation and would need a wait
  // that proves nothing the sweep does not already prove on a settled page.
  assert.deepEqual(errors.slice(errorsBefore), [], "console errors during the click chain");
});

// stayedSpa() is only meaningful if a real reload clears the sentinel, so that
// is checked rather than assumed. Without this, a broken markSpa/stayedSpa pair
// would make the chain above pass no matter what the router did.
test("a full page load clears the SPA sentinel", async () => {
  await visit(page, "/");
  await markSpa(page);
  assert.equal(await stayedSpa(page), true);
  await visit(page, "/about");
  assert.equal(await stayedSpa(page), false);
});

// The locale prefix is what internal links historically dropped, and it drops on
// the SECOND hop as readily as the first, so the chain is walked under a prefix
// too. LocaleLink exists for exactly this.
//
// What proves the prefix survived is the anchor lookup inside clickTo: a
// LocaleLink that stopped prefixing renders href="/about" on a /de/ page, and
// there is then no /de/about to click. The lang assertion is a cheaper tripwire
// for something narrower, since the only runtime writer of
// document.documentElement.lang is LanguageSwitcher: it fires if an ordinary nav
// click ever routes through a locale switch.
test("client-side navigation keeps the locale prefix", async () => {
  const locale = advertisedLocales.find((l) => l !== SOURCE_LOCALE);
  await visit(page, `/${locale}/`);
  await markSpa(page);

  const errorsBefore = errors.length;
  let previousH1 = (await page.locator("h1").first().innerText()).trim();
  for (const slug of ["about", "faq", "services"]) {
    previousH1 = await clickTo(`/${locale}/${slug}`, previousH1);
    assert.equal(await stayedSpa(page), true, `/${locale}/${slug} triggered a full reload`);
    assert.equal(
      await page.evaluate(() => document.documentElement.lang),
      locale,
      `<html lang> drifted off ${locale} during client navigation`,
    );
  }
  assert.deepEqual(errors.slice(errorsBefore), [], `console errors during the ${locale} click chain`);
});

// --- the one route deliberately left out of the sweep ----------------------

// dist/404.html is prerendered like every page above but deliberately absent
// from the sitemap (prerender.mjs: noindex, no canonical, no hreflang), so the
// derived route list cannot contain it. Named here rather than left to vanish
// into a filter, because "everything in the sitemap" and "everything we emit"
// differ by exactly this one document. Two reasons it is not swept:
//
// 1. It fails the sweep's checks BY DESIGN: no canonical to match a <loc>
//    against, and being noindex is the point of it.
//
// 2. Its 404 STATUS cannot be tested through this harness at all. `vite preview`
//    answers unknown paths with dist/index.html and a 200 (verified: GET
//    /definitely-not-a-route returns the homepage, HTTP 200), the soft-404
//    behaviour production was changed to stop doing (terraform/cdn.tf maps 404
//    -> /404.html with response_code 404). Asserting 404 would fail a correct
//    build and asserting 200 would enshrine the bug, so it is stated, not faked.
//
// The document, its head contract and the NotFound view have their own suite in
// this directory, which is where assertions about them belong. One line stays
// here because this page is the sweep's blind spot: if that suite ever goes, the
// 404 page still has to render.
test("the one page outside the sitemap still renders clean", async () => {
  const errorsBefore = errors.length;
  const response = await visit(page, "/404.html");
  const raw = await response.text();

  // A 200 proves little here (reason 2 above), so identity is pinned on the
  // property that keeps this page out of the sitemap and out of the sweep: it is
  // the one emitted document with no canonical link. The SPA shell has one, so
  // if this stops being the 404 document the assertion says so instead of
  // quietly testing the homepage.
  assert.equal(response.status(), 200, "dist/404.html was not served as a file");
  assert.ok(
    !/<link\b[^>]*rel="canonical"/.test(raw),
    "the document served for /404.html declares a canonical, so it is not the 404 page",
  );
  assert.equal(await page.locator("h1").count(), 1);
  assert.deepEqual(errors.slice(errorsBefore), [], "console errors on the 404 page");
});
