################################################################################
# Storyblok STRUCTURE as code — space 288632938663524 (EU, mapi.storyblok.com)
#
# Managed here: component definitions (schemas, below) + the rebuild webhook.
# NOT managed here: stories/content — the labd/storyblok provider has no story
# resource; content lives in the CMS (marketing pages seeded as DRAFT via
# scripts/seed-storyblok-pages.mjs). Secrets (var.token, var.storyblok_webhook_url_token)
# have no defaults and are passed at plan/apply via op (see terraform/README /
# the deploy pipeline). Values land in state, never in code. Review every plan
# diff on these resources before applying.
################################################################################

################################################################################
# Rebuild webhook -> Lambda function URL (webhook.tf) -> GitHub Actions deploy
################################################################################

resource "storyblok_webhook" "rebuild" {
  space_id    = var.space_id
  name        = "storyblok-rebuild"
  description = "Rebuild agusgonzaleznic.com on content changes (GitHub Actions deploy.yml)"
  endpoint    = "${aws_lambda_function_url.webhook.function_url}?token=${var.storyblok_webhook_url_token}"

  actions = [
    "story.published",
    "story.unpublished",
    "story.deleted",
    "story.moved",
  ]
}

############################################################################################################################################################
# Components — synced 1:1 from the live Management API on 2026-07-17 (post the
# marketing-page → Storyblok migration; schemas created/updated via
# scripts/seed-storyblok-pages.mjs). Regenerated by scratchpad/sync-tf.mjs.
# Editing schemas in the UI? Re-sync this file before applying, or the apply
# clobbers the UI change. Review every plan diff on these resources.
################################################################################

resource "storyblok_component" "about_block" {
  space_id     = var.space_id
  name         = "about_block"
  display_name = "About Block"
  icon         = "block-image"
  is_root      = false
  is_nestable  = true

  schema = {
    heading      = { type = "text", position = 0, display_name = "Heading", required = true }
    image_alt    = { type = "text", position = 1, display_name = "Image Alt Text" }
    paragraphs   = { type = "bloks", position = 2, display_name = "Paragraphs", restrict_components = true, component_whitelist = ["text_item"] }
    footnote     = { type = "textarea", position = 3, display_name = "Footnote" }
    show_section = { type = "boolean", position = 4, display_name = "Show This Section", default_value = "true" }
  }
}

resource "storyblok_component" "blog_post" {
  space_id     = var.space_id
  name         = "blog_post"
  display_name = "Blog Post"
  is_root      = true
  is_nestable  = false

  schema = {
    content_tab        = { type = "tab", position = 0, display_name = "Content", keys = ["title", "excerpt", "body", "cover_image", "published_date", "original_url"] }
    title              = { type = "text", position = 1, display_name = "Title", required = true }
    excerpt            = { type = "textarea", position = 2, display_name = "Excerpt", description = "Short teaser shown on the blog index and used as default meta description", required = true, max_length = 200 }
    body               = { type = "richtext", position = 3, display_name = "Body", required = true }
    cover_image        = { type = "asset", position = 4, display_name = "Cover Image", filetypes = ["images"] }
    published_date     = { type = "datetime", position = 5, display_name = "Published Date", description = "Original publication date", required = true }
    original_url       = { type = "text", position = 6, display_name = "Original URL", description = "If republished (e.g. from Medium), the original URL" }
    seo_tab            = { type = "tab", position = 7, display_name = "SEO", keys = ["seo_title", "seo_description", "canonical_override"] }
    seo_title          = { type = "text", position = 8, display_name = "SEO Title", max_length = 60 }
    seo_description    = { type = "textarea", position = 9, display_name = "SEO Description", max_length = 160 }
    canonical_override = { type = "text", position = 10, display_name = "Canonical Override", description = "Leave empty — self-canonical by default" }
  }
}

resource "storyblok_component" "contact_block" {
  space_id     = var.space_id
  name         = "contact_block"
  display_name = "Contact Block"
  icon         = "block-email"
  is_root      = false
  is_nestable  = true

  schema = {
    heading                = { type = "text", position = 0, display_name = "Heading" }
    subheading             = { type = "textarea", position = 1, display_name = "Subheading" }
    get_in_touch_heading   = { type = "text", position = 2, display_name = "Get in Touch Heading" }
    response_time_heading  = { type = "text", position = 3, display_name = "Response Time Heading" }
    response_time_text     = { type = "textarea", position = 4, display_name = "Response Time Text" }
    discovery_call_heading = { type = "text", position = 5, display_name = "Discovery Call Heading" }
    discovery_call_text    = { type = "textarea", position = 6, display_name = "Discovery Call Text" }
    show_section           = { type = "boolean", position = 7, display_name = "Show This Section", default_value = "true" }
  }
}

resource "storyblok_component" "engagement_item" {
  space_id     = var.space_id
  name         = "engagement_item"
  display_name = "Engagement"
  icon         = "block-comment"
  is_root      = false
  is_nestable  = true

  schema = {
    role    = { type = "text", position = 0, display_name = "Role", required = true }
    context = { type = "text", position = 1, display_name = "Context" }
    sketch  = { type = "textarea", position = 2, display_name = "Sketch", required = true }
  }
}

resource "storyblok_component" "faq_block" {
  space_id     = var.space_id
  name         = "faq_block"
  display_name = "FAQ Block"
  icon         = "block-comment"
  is_root      = false
  is_nestable  = true

  schema = {
    heading      = { type = "text", position = 0, display_name = "Heading" }
    subheading   = { type = "textarea", position = 1, display_name = "Subheading" }
    faqs         = { type = "bloks", position = 2, display_name = "FAQs", restrict_components = true, component_whitelist = ["faq_item"] }
    show_section = { type = "boolean", position = 3, display_name = "Show This Section", default_value = "true" }
  }
}

resource "storyblok_component" "faq_item" {
  space_id     = var.space_id
  name         = "faq_item"
  display_name = "FAQ Item"
  icon         = "block-comment"
  is_root      = false
  is_nestable  = true

  schema = {
    question = { type = "text", position = 0, display_name = "Question", required = true }
    answer   = { type = "textarea", position = 1, display_name = "Answer", required = true }
  }
}

resource "storyblok_component" "hero_block" {
  space_id     = var.space_id
  name         = "hero_block"
  display_name = "Hero Block"
  icon         = "block-block"
  is_root      = false
  is_nestable  = true

  schema = {
    badge            = { type = "text", position = 0, display_name = "Badge" }
    subheading       = { type = "textarea", position = 1, display_name = "Subheading" }
    cta_text         = { type = "text", position = 2, display_name = "CTA Text" }
    industries_label = { type = "text", position = 3, display_name = "Industries Label" }
    industries       = { type = "textarea", position = 4, display_name = "Industries (one per line, not translated)" }
    image_alt        = { type = "text", position = 5, display_name = "Image Alt Text" }
    show_section     = { type = "boolean", position = 6, display_name = "Show This Section", default_value = "true" }
  }
}

resource "storyblok_component" "how_i_work_block" {
  space_id     = var.space_id
  name         = "how_i_work_block"
  display_name = "How I Work Block"
  icon         = "block-sticker"
  is_root      = false
  is_nestable  = true

  schema = {
    heading      = { type = "text", position = 0, display_name = "Heading" }
    values       = { type = "bloks", position = 1, display_name = "Values", restrict_components = true, component_whitelist = ["value_item"] }
    show_section = { type = "boolean", position = 2, display_name = "Show This Section", default_value = "true" }
  }
}

resource "storyblok_component" "impact_block" {
  space_id     = var.space_id
  name         = "impact_block"
  display_name = "Impact Block"
  icon         = "block-table"
  is_root      = false
  is_nestable  = true

  schema = {
    timeline_heading = { type = "text", position = 0, display_name = "Timeline Heading" }
    timeline         = { type = "bloks", position = 1, display_name = "Timeline", restrict_components = true, component_whitelist = ["timeline_item"] }
    stats_heading    = { type = "text", position = 2, display_name = "Stats Heading" }
    stats_subheading = { type = "textarea", position = 3, display_name = "Stats Subheading" }
    stats            = { type = "bloks", position = 4, display_name = "Stats", restrict_components = true, component_whitelist = ["stat_item"] }
    show_section     = { type = "boolean", position = 5, display_name = "Show This Section", default_value = "true" }
  }
}

resource "storyblok_component" "page" {
  space_id     = var.space_id
  name         = "page"
  display_name = "Page"
  icon         = "block-doc"
  is_root      = true
  is_nestable  = false

  schema = {
    body            = { type = "bloks", position = 0, display_name = "Page Content", restrict_components = true, component_whitelist = ["hero_block", "about_block", "philosophy_block", "how_i_work_block", "services_block", "impact_block", "testimonials_block", "faq_block", "contact_block"] }
    seo_title       = { type = "text", position = 1, display_name = "SEO Title", max_length = 60 }
    seo_description = { type = "textarea", position = 2, display_name = "SEO Description", max_length = 160 }
    og_image        = { type = "asset", position = 3, display_name = "Social Media Image", filetypes = ["images"] }
  }
}

resource "storyblok_component" "philosophy_block" {
  space_id     = var.space_id
  name         = "philosophy_block"
  display_name = "Philosophy Block"
  icon         = "block-sticker"
  is_root      = false
  is_nestable  = true

  schema = {
    heading      = { type = "text", position = 0, display_name = "Heading" }
    subheading   = { type = "textarea", position = 1, display_name = "Subheading" }
    principles   = { type = "bloks", position = 2, display_name = "Principles", restrict_components = true, component_whitelist = ["principle_item"] }
    show_section = { type = "boolean", position = 3, display_name = "Show This Section", default_value = "true" }
  }
}

resource "storyblok_component" "principle_item" {
  space_id     = var.space_id
  name         = "principle_item"
  display_name = "Principle"
  icon         = "block-sticker"
  is_root      = false
  is_nestable  = true

  schema = {
    icon        = { type = "option", position = 0, display_name = "Icon", options = [{ name = "Lightbulb", value = "Lightbulb" }, { name = "Cog", value = "Cog" }, { name = "Heart", value = "Heart" }, { name = "Target", value = "Target" }, { name = "ShieldCheck", value = "ShieldCheck" }, { name = "MessagesSquare", value = "MessagesSquare" }, { name = "Wrench", value = "Wrench" }, { name = "TrendingDown", value = "TrendingDown" }, { name = "Shield", value = "Shield" }, { name = "Rocket", value = "Rocket" }, { name = "Zap", value = "Zap" }, { name = "Users", value = "Users" }] }
    title       = { type = "text", position = 1, display_name = "Title", required = true }
    description = { type = "textarea", position = 2, display_name = "Description", required = true }
    color       = { type = "option", position = 3, display_name = "Color Theme", default_value = "accent", options = [{ name = "Accent", value = "accent" }, { name = "Primary", value = "primary" }] }
  }
}

resource "storyblok_component" "service_item" {
  space_id     = var.space_id
  name         = "service_item"
  display_name = "Service Item"
  icon         = "block-suitcase"
  is_root      = false
  is_nestable  = true

  schema = {
    title       = { type = "text", position = 0, display_name = "Title", required = true }
    subtitle    = { type = "text", position = 1, display_name = "Subtitle" }
    description = { type = "textarea", position = 2, display_name = "Description", required = true }
    features    = { type = "bloks", position = 3, display_name = "Features", restrict_components = true, component_whitelist = ["text_item"] }
    format      = { type = "text", position = 4, display_name = "Session Format" }
    best_for    = { type = "text", position = 5, display_name = "Best For" }
    featured    = { type = "boolean", position = 6, display_name = "Featured (Most Popular)", default_value = "false" }
  }
}

resource "storyblok_component" "services_block" {
  space_id     = var.space_id
  name         = "services_block"
  display_name = "Services Block"
  icon         = "block-suitcase"
  is_root      = false
  is_nestable  = true

  schema = {
    heading       = { type = "text", position = 0, display_name = "Heading" }
    subheading    = { type = "textarea", position = 1, display_name = "Subheading" }
    services      = { type = "bloks", position = 2, display_name = "Services", restrict_components = true, component_whitelist = ["service_item"] }
    bottom_prompt = { type = "textarea", position = 3, display_name = "Bottom Prompt" }
    show_section  = { type = "boolean", position = 4, display_name = "Show This Section", default_value = "true" }
  }
}

resource "storyblok_component" "stat_item" {
  space_id     = var.space_id
  name         = "stat_item"
  display_name = "Stat Item"
  icon         = "block-table-2"
  is_root      = false
  is_nestable  = true

  schema = {
    icon        = { type = "option", position = 0, display_name = "Icon", options = [{ name = "Lightbulb", value = "Lightbulb" }, { name = "Cog", value = "Cog" }, { name = "Heart", value = "Heart" }, { name = "Target", value = "Target" }, { name = "ShieldCheck", value = "ShieldCheck" }, { name = "MessagesSquare", value = "MessagesSquare" }, { name = "Wrench", value = "Wrench" }, { name = "TrendingDown", value = "TrendingDown" }, { name = "Shield", value = "Shield" }, { name = "Rocket", value = "Rocket" }, { name = "Zap", value = "Zap" }, { name = "Users", value = "Users" }] }
    value       = { type = "text", position = 1, display_name = "Value", required = true }
    label       = { type = "text", position = 2, display_name = "Label", required = true }
    description = { type = "textarea", position = 3, display_name = "Description" }
  }
}

resource "storyblok_component" "testimonials_block" {
  space_id     = var.space_id
  name         = "testimonials_block"
  display_name = "Testimonials Block"
  icon         = "block-comment"
  is_root      = false
  is_nestable  = true

  schema = {
    heading      = { type = "text", position = 0, display_name = "Heading" }
    subheading   = { type = "textarea", position = 1, display_name = "Subheading" }
    engagements  = { type = "bloks", position = 2, display_name = "Engagements", restrict_components = true, component_whitelist = ["engagement_item"] }
    note         = { type = "textarea", position = 3, display_name = "Confidentiality Note" }
    show_section = { type = "boolean", position = 4, display_name = "Show This Section", default_value = "true" }
  }
}

resource "storyblok_component" "text_item" {
  space_id     = var.space_id
  name         = "text_item"
  display_name = "Text"
  icon         = "block-text-l"
  is_root      = false
  is_nestable  = true

  schema = {
    text = { type = "textarea", position = 0, display_name = "Text", required = true }
  }
}

resource "storyblok_component" "timeline_item" {
  space_id     = var.space_id
  name         = "timeline_item"
  display_name = "Timeline Item"
  icon         = "block-table"
  is_root      = false
  is_nestable  = true

  schema = {
    period      = { type = "text", position = 0, display_name = "Period" }
    company     = { type = "text", position = 1, display_name = "Company" }
    role        = { type = "text", position = 2, display_name = "Role", required = true }
    achievement = { type = "textarea", position = 3, display_name = "Achievement", required = true }
  }
}

resource "storyblok_component" "value_item" {
  space_id     = var.space_id
  name         = "value_item"
  display_name = "Value"
  icon         = "block-sticker"
  is_root      = false
  is_nestable  = true

  schema = {
    icon        = { type = "option", position = 0, display_name = "Icon", options = [{ name = "Lightbulb", value = "Lightbulb" }, { name = "Cog", value = "Cog" }, { name = "Heart", value = "Heart" }, { name = "Target", value = "Target" }, { name = "ShieldCheck", value = "ShieldCheck" }, { name = "MessagesSquare", value = "MessagesSquare" }, { name = "Wrench", value = "Wrench" }, { name = "TrendingDown", value = "TrendingDown" }, { name = "Shield", value = "Shield" }, { name = "Rocket", value = "Rocket" }, { name = "Zap", value = "Zap" }, { name = "Users", value = "Users" }] }
    title       = { type = "text", position = 1, display_name = "Title", required = true }
    description = { type = "textarea", position = 2, display_name = "Description", required = true }
  }
}

################################################################################
# Import blocks — bind the live components (ids from the live Management API) to
# state. Terraform skips any already in state; remove after a clean apply.
################################################################################

import {
  to = storyblok_component.about_block
  id = "288632938663524/114859833011584"
}

import {
  to = storyblok_component.blog_post
  id = "288632938663524/194801325335725"
}

import {
  to = storyblok_component.contact_block
  id = "288632938663524/115709930016359"
}

import {
  to = storyblok_component.engagement_item
  id = "288632938663524/199184357610720"
}

import {
  to = storyblok_component.faq_block
  id = "288632938663524/199184366167267"
}

import {
  to = storyblok_component.faq_item
  id = "288632938663524/199184364500194"
}

import {
  to = storyblok_component.hero_block
  id = "288632938663524/114859830549882"
}

import {
  to = storyblok_component.how_i_work_block
  id = "288632938663524/199175472420050"
}

import {
  to = storyblok_component.impact_block
  id = "288632938663524/114859832917374"
}

import {
  to = storyblok_component.page
  id = "288632938663524/114527391321689"
}

import {
  to = storyblok_component.philosophy_block
  id = "288632938663524/114859833032065"
}

import {
  to = storyblok_component.principle_item
  id = "288632938663524/114859830578556"
}

import {
  to = storyblok_component.service_item
  id = "288632938663524/114859830553979"
}

import {
  to = storyblok_component.services_block
  id = "288632938663524/114859832982911"
}

import {
  to = storyblok_component.stat_item
  id = "288632938663524/114859830500728"
}

import {
  to = storyblok_component.testimonials_block
  id = "288632938663524/114859832339837"
}

import {
  to = storyblok_component.text_item
  id = "288632938663524/199184346195167"
}

import {
  to = storyblok_component.timeline_item
  id = "288632938663524/199184360355041"
}

import {
  to = storyblok_component.value_item
  id = "288632938663524/199175471916241"
}

################################################################################
# Forget the two components the marketing-page migration superseded
# (metric_item -> stat_item, testimonial_item -> engagement_item). They were
# already deleted from the space out-of-band, so they only linger in state.
# destroy = false forgets them from state WITHOUT a refresh (the provider 404s
# on a deleted component) and without re-issuing a delete. Remove these blocks
# after one clean apply.
################################################################################

removed {
  from = storyblok_component.metric_item
  lifecycle {
    destroy = false
  }
}

removed {
  from = storyblok_component.testimonial_item
  lifecycle {
    destroy = false
  }
}
